### ISSUE TITLE
Impossible to upload template

### ISSUE THREAD

**Issue by nlejeune** [zezutom/NiFiByExample#2]
Hi,

I use Nifi 1.7.1 and I tried to upload one of your templates.
I had this error message :  

Unable to Upload
The specified template is not in a valid format.

**Comment by zezutom** [comment]
Hello,
Thanks for your feedback. I haven't reviewed the code in a long time and your issue is a great reminder. Nevertheless, I've just tested my templates against the latest version of NiFi (1.8.0) and I did successfully import them.

Are you sure you are trying to upload XML in the raw format? For example, like this:
https://raw.githubusercontent.com/zezutom/NiFiByExample/master/templates/http_post/HTTP_POST_Examples.xml

**Comment by nlejeune** [comment]
The raw format was the solution thank you !
